--
-- PostgreSQL database dump
--

\restrict sLE1Dtrz2wHXupYMchFHvKkmGIQZQ8f2Mzc1aE663OrHS8xhuhpCCGE3wkkAD6f

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-31 21:49:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 865 (class 1247 OID 90399)
-- Name: assinatura_tipo; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.assinatura_tipo AS ENUM (
    'mensal',
    'anual'
);


ALTER TYPE public.assinatura_tipo OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 90403)
-- Name: assinatura; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assinaturas (
    id integer NOT NULL,
    nome character varying(64) NOT NULL,
    descricao character varying NOT NULL,
    preco real NOT NULL
);


ALTER TABLE public.assinaturas OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 90423)
-- Name: assinatura_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assinaturas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assinatura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 90433)
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias (
    id integer NOT NULL,
    nome character varying NOT NULL,
    produto_id integer
);


ALTER TABLE public.categorias OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 90386)
-- Name: produtos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produtos (
    id integer NOT NULL,
    nome character varying(64) NOT NULL,
    descricao character varying NOT NULL,
    preco real NOT NULL,
    foto character varying,
    quantidade integer NOT NULL
);


ALTER TABLE public.produtos OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 90421)
-- Name: produtos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produtos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 90374)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    nome character varying(64) NOT NULL,
    email character varying(64) NOT NULL,
    endereco character varying(64),
    login character varying(24) NOT NULL,
    senha character varying(256) NOT NULL,
    administrador boolean DEFAULT false NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 90422)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 90447)
-- Name: vendas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vendas (
    id integer NOT NULL,
    data_hora timestamp without time zone NOT NULL,
    produto_id integer NOT NULL,
    usuario_id integer NOT NULL
);


ALTER TABLE public.vendas OWNER TO postgres;


--
-- TOC entry 5049 (class 0 OID 0)
-- Dependencies: 224
-- Name: assinatura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assinatura_id_seq', 1, true);


--
-- TOC entry 5050 (class 0 OID 0)
-- Dependencies: 222
-- Name: produtos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produtos_id_seq', 1, true);


--
-- TOC entry 5051 (class 0 OID 0)
-- Dependencies: 223
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 1, false);


--
-- TOC entry 4883 (class 2606 OID 90413)
-- Name: assinatura assinatura_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assinaturas
    ADD CONSTRAINT assinatura_pkey PRIMARY KEY (id);


--
-- TOC entry 4885 (class 2606 OID 90441)
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (id);


--
-- TOC entry 4881 (class 2606 OID 90397)
-- Name: produtos produtos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produtos
    ADD CONSTRAINT produtos_pkey PRIMARY KEY (id);


--
-- TOC entry 4879 (class 2606 OID 90385)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4886 (class 2606 OID 90442)
-- Name: categoria FK_categoria_produto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT "FK_categoria_produto_id" FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- TOC entry 4887 (class 2606 OID 90454)
-- Name: vendas FK_vendas_produto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vendas
    ADD CONSTRAINT "FK_vendas_produto_id" FOREIGN KEY (produto_id) REFERENCES public.produtos(id);


--
-- TOC entry 4888 (class 2606 OID 90459)
-- Name: vendas FK_vendas_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vendas
    ADD CONSTRAINT "FK_vendas_usuario_id" FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


-- Completed on 2026-05-31 21:49:23

--
-- PostgreSQL database dump complete
--

\unrestrict sLE1Dtrz2wHXupYMchFHvKkmGIQZQ8f2Mzc1aE663OrHS8xhuhpCCGE3wkkAD6f

